### ISSUE TITLE
SOLID LOGIN: Implement the authentication

### ISSUE THREAD

**Issue by gjwgit** [anusii/solid#17]
Sub task of #11 

Make it modular.

**Comment by Zheyuan-Robert-Xu** [comment]
Made pull request https://github.com/anusii/keypod/pull/38

**Comment by gjwgit** [comment]
Move back to in-progress - need to migrate solid_auth code into solid so we don;t rely on sloid_auth.

**Comment by gjwgit** [comment]
Duplicate #11
