### ISSUE TITLE
SOLID LOGIN: Obtain the app version

### ISSUE THREAD

**Issue by gjwgit** [anusii/solid#18]
## Description

As per TODO note, implement the obtaining of the version in solid login.

**Comment by zheyxu** [comment]
The app version should be obtained from pubspec.yaml inb keyPod project? @gjwgit

**Comment by zheyxu** [comment]
Made pull request https://github.com/anusii/keypod/pull/40 and https://github.com/anusii/solid/pull/28

**Comment by gjwgit** [comment]
The description suggested that the version should be obtained from within `solid login`. That is, inside the `solid` package. 

At every step the aim is to make it easier for the app developer, not harder. 

With your approach every app  developer now needs to obtain the version themselves. It would be better if it is obtained within the solid package (so we do the hard work once) and not in the app (where every app developer has to do the hard work every time).
