### ISSUE TITLE
SOLID LOGIN: Allow a `skip login` option

### ISSUE THREAD

**Issue by gjwgit** [anusii/solid#42]
## Description

Add an option to allow the login to be skipped with something like `SolidLogin(requireLogin: false)`. 

If requireLogin is false then there is a CONTINUE button on the app's login screen to go directly to the `child`.

If the user clicks LOGIN and then CANCEL in the browser popup or enters the wrong credentials, then return to the Login screen.

## Why

So that an app that may not require data to be retrieved from or saved to a Pod, but supports it if logged in, can operate without the need of a Pod or logging in.  The btsim and innerpod apps are examples of this use case.

**Comment by zheyxu** [comment]
Made pull request https://github.com/anusii/solid/pull/45
https://github.com/anusii/keypod/pull/43

**Comment by zheyxu** [comment]
Made pull request Made pull request https://github.com/anusii/solid/pull/45
https://github.com/anusii/keypod/pull/43

**Comment by gjwgit** [comment]
Where do I find the Continue button?

**Comment by gjwgit** [comment]
Great addition of the Cancel button on the `Logging in...` popup. On Android at the moment this login is failing. At least I now have an option to return to the Login page. Thanks.

**Comment by gjwgit** [comment]
Tested and working well. I have updated a few bits here and there. The CONTINUE button swapped with the GET A POD button since the latter will disappear once another issue is completed.

**Comment by zheyxu** [comment]
> Great addition of the Cancel button on the `Logging in...` popup. On Android at the moment this login is failing. At least I now have an option to return to the Login page. Thanks.

Hi @gjwgit, the issue should be fixed at the existing issue https://github.com/anusii/solid/issues/43. According to previous experience, some configuration files in android folder should be edited.

**Comment by gjwgit** [comment]
There was no issue. Sorry for the confusion. I changed the code to put the CONTINUE button where I think it belongs longer term.

**Comment by gjwgit** [comment]
Can be merged and closed once @anushkavidanage or @NinadBhat have reviewed. Thanks.

**Comment by gjwgit** [comment]
Merged. Can be closed.
