### ISSUE TITLE
SOLID LOGIN: On my Android device the Login is stuck at Logging in...

### ISSUE THREAD

**Issue by gjwgit** [anusii/solid#43]
## Description

On both keypod and innerpod on clicking the Login button the process is stuck at `Logging in...`

![Image](https://github.com/anusii/solid/assets/1681429/af2722db-405a-4bfd-b4d8-da754111c3b8)

Seems to be related to:

```
W/WindowOnBackDispatcher( 1611): OnBackInvokedCallback is not enabled for the application.
W/WindowOnBackDispatcher( 1611): Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
I/flutter ( 1611): server started 4400
I/UrlLauncher( 1611): component name for https://pods.solidcommunity.au/.oidc/auth?response_type=code&scope=openid+openid+profile+offline_access&client_id=lMAfacOQy-NBhn5rZUI39&redirect_uri=http%3A%2F%2Flocalhost%3A4400%2F&response_mode=query&state=TUlZepEpEVCOYmzYR7Q8&code_challenge_method=S256&code_challenge=3Zh7eg6GN1BcAfzPlyl66cYTadwyFkOiutK35JP0u-8 is null
I/UrlLauncher( 1611): component name for https://flutter.dev is null
E/flutter ( 1611): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Could not launch https://pods.solidcommunity.au/.oidc/auth?response_type=code&scope=openid+openid+profile+offline_access&client_id=lMAfacOQy-NBhn5rZUI39&redirect_uri=http%3A%2F%2Flocalhost%3A4400%2F&response_mode=query&state=TUlZepEpEVCOYmzYR7Q8&code_challenge_method=S256&code_challenge=3Zh7eg6GN1BcAfzPlyl66cYTadwyFkOiutK35JP0u-8
E/flutter ( 1611): #0      authenticate.urlLauncher (package:solid_auth/solid_auth_client.dart:175:9)
E/flutter ( 1611): <asynchronous suspension>
E/flutter ( 1611): 
```

**Comment by gjwgit** [comment]
https://github.com/flutter/flutter/issues/132504

**Comment by gjwgit** [comment]
Seems to work okay with podnotes but not keypod.

**Comment by zheyxu** [comment]
https://github.com/flutter/plugins/tree/master_archive/packages/url_launcher/url_launcher#android

Starting from API 30 Android requires package visibility configuration in your AndroidManifest.xml otherwise canLaunchUrl will return false.

**Comment by zheyxu** [comment]
<img width="340" alt="Screenshot 2024-01-26 at 4 50 39 pm" src="https://github.com/anusii/solid/assets/79696631/5d3a7973-5159-4a56-8461-9105b3a8306c">
Enable login in Android app

**Comment by gjwgit** [comment]
Please see the PR's. Seems to be requesting many more permissions and have added much more code that is actually required to fix this issue?

**Comment by zheyxu** [comment]
The pull request https://github.com/anusii/solid/pull/47 has already be merged.
