### ISSUE TITLE
SOLID LOGIN: Redesign buttons

### ISSUE THREAD

**Issue by gjwgit** [anusii/solid#44]
## Description

The current innerpod looks great with 3 buttons and a visit link. This task updates to 4 buttons, all the same size, and with only 3 buttons if loginRequired is true.

![Image](https://github.com/anusii/solid/assets/1681429/529c327e-f548-42c7-aaa4-a40e0a309c6a)

- [x] I propose we turn all 4 into buttons: LOGIN, CONTINUE, GET A POD, INFO.
- [x] When CONTINUE is not shown move GET A POD from bottom left to the top right in place of CONTINUE 
- [x] All buttons should be the same size irrespective of the number of buttons
- [x] The Visit link becomes a help or further info button, default label is INFO
- [x] The text for each button can be overriden in the SolidLogin() call

**Comment by zheyxu** [comment]
Hi @gjwgit, should the Visit link (the last line (hyperlink) in the picture) be removed?

**Comment by gjwgit** [comment]
Yes, the Visit link should be removed. It is essentially replace by the INFO button. Thanks.

**Comment by zheyxu** [comment]
Images of three or four buttons.
<img width="1417" alt="Screenshot 2024-01-31 at 8 26 28 pm" src="https://github.com/anusii/solid/assets/79696631/7431b0d6-44af-458e-90dd-04298ef9698d">
<img width="1409" alt="Screenshot 2024-01-31 at 8 25 51 pm" src="https://github.com/anusii/solid/assets/79696631/e4906821-25a6-444a-b7c7-e80f8b715fae">

**Comment by gjwgit** [comment]
Looks great. Thanks. I'll review the PR.

**Comment by gjwgit** [comment]
Working well. @anushkavidanage to approve then @zheyxu to merge.

**Comment by gjwgit** [comment]
Can be closed.
